lang: es

project:
  type: website
  output-dir: docs

website:
  title: "David Medina Núñez"
  navbar:
    left:
      - href: index.qmd
        text: Sobre mí
      - href: formacion.qmd
        text: Formación
      - href: experiencia.qmd
        text: Experiencia laboral
      - href: competencias.qmd
        text: Competencias
      - href: investigacion.qmd
        text: Seminarios e Investigación
      - href: proyectos.qmd
        text: Proyectos

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
